import { HazardReport, Donation, Volunteer } from '../types';

export const mockReports: HazardReport[] = [
  {
    id: '1',
    title: 'High Tide Alert - Marina Beach',
    description: 'Unusual wave patterns observed near Marina Beach. Water level rising rapidly.',
    location: 'Marina Beach, Chennai',
    latitude: 13.0499,
    longitude: 80.2824,
    severity: 'high',
    status: 'verified',
    submittedBy: 'Rajesh Kumar',
    submittedAt: new Date('2025-11-09T14:30:00'),
  },
  {
    id: '2',
    title: 'Oil Spill Detected',
    description: 'Small oil spill noticed near fishing harbor. Affecting local marine life.',
    location: 'Visakhapatnam Harbor',
    latitude: 17.6869,
    longitude: 83.2185,
    severity: 'critical',
    status: 'pending',
    submittedBy: 'Priya Sharma',
    submittedAt: new Date('2025-11-10T08:15:00'),
  },
  {
    id: '3',
    title: 'Coastal Erosion',
    description: 'Significant beach erosion observed after recent storm.',
    location: 'Puri Beach, Odisha',
    latitude: 19.8135,
    longitude: 85.8312,
    severity: 'medium',
    status: 'verified',
    submittedBy: 'Amit Patel',
    submittedAt: new Date('2025-11-08T16:45:00'),
  },
  {
    id: '4',
    title: 'Unusual Fish Behavior',
    description: 'Large schools of fish swimming in circles near shore.',
    location: 'Kovalam Beach, Kerala',
    latitude: 8.4004,
    longitude: 76.9790,
    severity: 'low',
    status: 'pending',
    submittedBy: 'Lakshmi Nair',
    submittedAt: new Date('2025-11-10T10:20:00'),
  },
  {
    id: '5',
    title: 'Strong Currents Warning',
    description: 'Dangerous rip currents observed. Multiple swimmers rescued.',
    location: 'Goa Beach',
    latitude: 15.2993,
    longitude: 74.1240,
    severity: 'high',
    status: 'resolved',
    submittedBy: 'John D\'Souza',
    submittedAt: new Date('2025-11-07T11:30:00'),
  },
];

export const mockDonations: Donation[] = [
  {
    id: '1',
    amount: 5000,
    donorName: 'Sunita Reddy',
    date: new Date('2025-11-09'),
    purpose: 'Ocean Monitoring Equipment',
    status: 'completed',
  },
  {
    id: '2',
    amount: 10000,
    donorName: 'Tech Corp India',
    date: new Date('2025-11-08'),
    purpose: 'Volunteer Training Program',
    status: 'completed',
  },
  {
    id: '3',
    amount: 2500,
    donorName: 'Anonymous',
    date: new Date('2025-11-10'),
    purpose: 'General Fund',
    status: 'completed',
  },
  {
    id: '4',
    amount: 7500,
    donorName: 'Coastal Community Foundation',
    date: new Date('2025-11-07'),
    purpose: 'Research & Development',
    status: 'completed',
  },
  {
    id: '5',
    amount: 3000,
    donorName: 'Marine Conservancy Group',
    date: new Date('2025-11-06'),
    purpose: 'Emergency Response',
    status: 'pending',
  },
];

export const mockVolunteers: Volunteer[] = [
  {
    id: '1',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@example.com',
    phone: '+91 98765 43210',
    location: 'Mumbai',
    skills: ['First Aid', 'Swimming', 'Communication'],
    status: 'active',
    joinedAt: new Date('2025-09-15'),
  },
  {
    id: '2',
    name: 'Kavya Iyer',
    email: 'kavya.iyer@example.com',
    phone: '+91 98765 43211',
    location: 'Chennai',
    skills: ['Data Analysis', 'Research', 'Photography'],
    status: 'active',
    joinedAt: new Date('2025-08-20'),
  },
  {
    id: '3',
    name: 'Rahul Verma',
    email: 'rahul.verma@example.com',
    phone: '+91 98765 43212',
    location: 'Visakhapatnam',
    skills: ['Navigation', 'Equipment Maintenance'],
    status: 'pending',
    joinedAt: new Date('2025-11-05'),
  },
  {
    id: '4',
    name: 'Sneha Desai',
    email: 'sneha.desai@example.com',
    phone: '+91 98765 43213',
    location: 'Goa',
    skills: ['Social Media', 'Community Outreach', 'Translation'],
    status: 'active',
    joinedAt: new Date('2025-10-10'),
  },
  {
    id: '5',
    name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    phone: '+91 98765 43214',
    location: 'Kochi',
    skills: ['Diving', 'Marine Biology', 'First Aid'],
    status: 'inactive',
    joinedAt: new Date('2025-07-01'),
  },
];

export const mockAnalyticsData = {
  hazardTrends: [
    { month: 'May', reports: 45, severity: 2.3 },
    { month: 'Jun', reports: 52, severity: 2.6 },
    { month: 'Jul', reports: 68, severity: 2.8 },
    { month: 'Aug', reports: 71, severity: 3.1 },
    { month: 'Sep', reports: 58, severity: 2.4 },
    { month: 'Oct', reports: 63, severity: 2.7 },
    { month: 'Nov', reports: 48, severity: 2.2 },
  ],
  topKeywords: [
    { keyword: 'high tide', count: 145 },
    { keyword: 'erosion', count: 98 },
    { keyword: 'oil spill', count: 67 },
    { keyword: 'strong currents', count: 54 },
    { keyword: 'marine life', count: 43 },
  ],
  sentimentAnalysis: {
    positive: 23,
    neutral: 45,
    negative: 32,
  },
  donationTrends: [
    { month: 'May', amount: 125000 },
    { month: 'Jun', amount: 145000 },
    { month: 'Jul', amount: 132000 },
    { month: 'Aug', amount: 158000 },
    { month: 'Sep', amount: 171000 },
    { month: 'Oct', amount: 189000 },
    { month: 'Nov', amount: 95000 },
  ],
};

export const mockSocialMediaPosts = [
  {
    id: '1',
    platform: 'Twitter',
    author: '@CoastalWatch',
    content: 'High waves reported at Marina Beach. Stay safe and avoid swimming. #OceanSafety #Chennai',
    timestamp: new Date('2025-11-10T09:30:00'),
    sentiment: 'warning',
    location: 'Chennai',
  },
  {
    id: '2',
    platform: 'Facebook',
    author: 'Goa Beach Safety',
    content: 'Beautiful calm waters today! Perfect for swimming and water sports. 🌊',
    timestamp: new Date('2025-11-10T08:15:00'),
    sentiment: 'positive',
    location: 'Goa',
  },
  {
    id: '3',
    platform: 'Instagram',
    author: '@OceanGuardian',
    content: 'Spotted unusual algae bloom near Vizag harbor. Monitoring the situation closely.',
    timestamp: new Date('2025-11-10T07:45:00'),
    sentiment: 'alert',
    location: 'Visakhapatnam',
  },
  {
    id: '4',
    platform: 'Twitter',
    author: '@KeralaTourism',
    content: 'Monsoon aftermath: Our beaches are recovering well. Nature is healing! 🌴',
    timestamp: new Date('2025-11-09T18:20:00'),
    sentiment: 'positive',
    location: 'Kerala',
  },
];
